<a href="https://colab.research.google.com/github/macasave12-boop/mi-tarea-numpy-pandas/blob/main/Bono_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Manejo de módulos integrados

**NumPy:** Se usa principalmente para trabajar con datos numéricos de forma rápida, eficiente y estructurada. Un objeto tipo numpy es un arreglo base para hacer matemáticas y manipular datos en Python.

**Uso en ciencia de datos**


*   Manipulación de vectores y matrices
*   Álgebra lineal y cálculo matricial.
* Operaciones estadísticas y matemáticas.
* Procesamiento rápido de grandes volúmenes de datos numéricos.
* Base para librerías como TensorFlow, Scikit-learn y Pandas.

**Ventajas**
* Muy rápido y eficiente gracias a su implementación en C.
* Consume menos memoria que las listas tradicionales de Python.
* Facilita operaciones matemáticas complejas con pocas líneas de código.
* Ideal para algoritmos de
* Machine Learning y análisis numérico.
* Permite vectorización, evitando ciclos for lentos.

**Desventajas**
* Trabaja principalmente con datos numéricos homogéneos.
* Menos intuitivo para manipular datos tabulares.
* No posee herramientas avanzadas de limpieza o análisis de datos estructurados.
* Puede ser complejo para principiantes en álgebra matricial.

**Pandas:** Se usa para trabajar con datos estructurados (como tablas de Excel o bases de datos). Un objeto tipo pandas permite cargar, limpiar, transformar y analizar datos. La usamos para base de datos relacionales.

**Uso en ciencia de datos**

* Limpieza y transformación de datos.
* Lectura de archivos CSV, Excel o bases de datos.
* Filtrado, agrupación y análisis estadístico.
* Preparación de datos antes de entrenar modelos.
* Exploración y visualización preliminar de información.

**Ventajas**

* Muy fácil de usar para análisis de datos.
* Permite trabajar con columnas nombradas y distintos tipos de datos.
* Excelente para limpieza y preprocesamiento.
* Integra funciones estadísticas y de agrupación.
* Compatible con NumPy y Scikit-learn.

**Desventajas**

* Más lento que NumPy en cálculos numéricos masivos.
* Consume más memoria.
* No es la mejor opción para operaciones matemáticas muy complejas.
* Puede volverse ineficiente con datasets extremadamente grandes.

La diferencia entre **NumPy** y **Pandas** radica en su propósito y nivel de uso. NumPy es una librería enfocada en el cálculo numérico eficiente mediante arrays multidimensionales, ideal para operaciones matemáticas rápidas, álgebra lineal y procesamiento de datos puramente numéricos; mientras que Pandas es una librería de más alto nivel diseñada para la manipulación y análisis de datos estructurados, como tablas tipo Excel o bases de datos, permitiendo trabajar con columnas con nombres, datos de distintos tipos, limpieza, filtrado y agrupación; en la práctica, Pandas se apoya internamente en NumPy, por lo que ambos se complementan y se utilizan juntos en la mayoría de flujos de análisis de datos.

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([[1, 2], [3, 4], [1, 2]])
print(a)
print(b)

[1 2 3 4]
[[1 2]
 [3 4]
 [1 2]]

In [ ]:
b*2

array([[2, 4],
       [6, 8],
       [2, 4]])

In [ ]:
lista = [1, 2, 3]
arr = np.array([1, 2, 3])

In [ ]:
lista*2

[1, 2, 3, 1, 2, 3]

In [ ]:
arr*2 #Hay una interpretación de los arreglos de tipo Numpy más apegados a lo que vemos en los
# objetos matemáticos como los vectores

array([2, 4, 6])

In [ ]:
arr.shape

(3,)

In [ ]:
b.shape #Arreglo de tres componentes cada uno con dos elementos

(3, 2)

In [ ]:
arr.ndim

1

In [ ]:
b.ndim #Número de elementos por cada componente

2

In [ ]:
b.dtype

dtype('int64')

In [ ]:
b.size # Cantidad de elementos de todas las componentes

6

**Arreglos especiales:**

In [ ]:
np.zeros((2, 3)) #Todo lleno de cero: 2 componentes y 3 elementos por componente

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2, 3)) #Todo lleno de uno: 2 componentes y 3 elementos por componente

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye(3) #La matriz identidad de una matriz cuadrada de tamaño 3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.arange(0, 10, 2) # Del 0 hasta el 10 (sin tomar el 10), separado por 2

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(0, 1, 5) # 5 elementos quistantes entre el 0 y el 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
arry = np.array([10, 20, 30, 40])
arry

array([10, 20, 30, 40])

In [ ]:
arry[-1]

np.int64(40)

In [ ]:
arry[0:2] #Tomando del índice 0 al 2 (sin tomar el 2)

array([10, 20])

In [ ]:
matri = np.array([[1,2,3], [4,5,6]])

In [ ]:
matri[0,1] # El índice 1 de la 0-ésima fila

np.int64(2)

In [ ]:
matri[:,0] # Es la 0-ésima columna

array([1, 4])

In [ ]:
matri[1:]

array([[4, 5, 6]])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b

array([5, 7, 9])

In [ ]:
a * b #Prodcuto de Hadamard entre dos arreglos

array([ 4, 10, 18])

In [ ]:
matri1 = np.array([[2,3,3], [4,5,6]])
matri1 * matri #Producto de Hadamard

array([[ 2,  6,  9],
       [16, 25, 36]])

In [ ]:
[x * 2 for x in lista]

[2, 4, 6]

**Ejemplo de Numpy:**

In [ ]:
c = np.array([1.65, 1.58, 1.82, 1.70, 1.50, 1.82, 1.74])
print(np.mean(c), np.median(c), np.std(c), np.sum(c), np.min(c), np.max(c))

1.6871428571428573 1.7 0.11093296376181246 11.81 1.5 1.82

**Manipulación de arreglos**

In [ ]:
d = np.array([1,2,3,4,5,6]) #Inicialmente tiene 6 elementos de un elemento cada una
d.reshape(2,3) # Cambia a 2 componentes cada una con 3 elementos

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([d,a]) # Concatenar arreglos

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [ ]:
np.concatenate(d.reshape(2,3))

array([1, 2, 3, 4, 5, 6])

In [ ]:
d.reshape(2,3).flatten() # Vectoriza la matriz

array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]]) # Multiplicación de matrices

np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [ ]:
np.linalg.inv(a) # Inversa de una matriz

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
np.linalg.matrix_transpose(a)

array([[1, 3],
       [2, 4]])

In [ ]:
np.random.rand(10) #Genera 10 valores de una distribución uniforme en el intervalo (0,1)

array([0.92073515, 0.96039185, 0.20277254, 0.27593294, 0.15637264,
       0.3376347 , 0.99993938, 0.04276027, 0.08019189, 0.43219707])

In [ ]:
np.random.randint(0,10) #Genera un valor entero entre 0 y el entero anterior al 10

2

In [ ]:
np.random.randn(8) # Genera 8 valores aletorios de una distribución normal con
# media 0 y desviación estándar 1

array([ 0.7562415 ,  1.54722161, -0.7065737 ,  0.57162349, -0.33819682,
       -0.81976078, -0.10892237,  0.31334888])

In [ ]:
e = np.array([1,2,3,4,5]) # Filtrado y condiciones
f = e[e > 3]
f

array([4, 5])

In [ ]:
e[(e >2) & (e < 5)] #Note que el y es &. El o es |

array([3, 4])

In [ ]:
np.where(e > 3, 1, 0) # Donde e>3 anotamos un 1. Donde no, un 0

array([0, 0, 0, 1, 1])

In [ ]:
np.where(e > 3, 1, e) #Los valores que no queremos reemplazar, anotamos el mismo objeto

array([1, 2, 3, 1, 1])

**Ahora con pandas**

In [ ]:
import pandas as pd

In [ ]:
s = pd.Series([10, 20, 30]) # Vector columna
s

0    10
1    20
2    30
dtype: int64

In [ ]:
df = pd.DataFrame({
    'nombre': ['Ana', 'Luis', 'Carlos', 'Marta'],
    'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá'],
    'edad': [23, 30, 35, 28],
    'salario': [1500, 2000, 3000, 2500]
}) # Creando data.frames
df

   nombre    ciudad  edad  salario
0     Ana    Bogotá    23     1500
1    Luis  Medellín    30     2000
2  Carlos      Cali    35     3000
3   Marta    Bogotá    28     2500

In [ ]:
salario_promedio = df['salario'].mean()
print(f"El salario promedio es: {salario_promedio}")

El salario promedio es: 2250.0

In [ ]:
df.head(2)

  nombre    ciudad  edad  salario
0    Ana    Bogotá    23     1500
1   Luis  Medellín    30     2000

In [ ]:
df.info() # Tipos de datos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nombre   4 non-null      object
 1   ciudad   4 non-null      object
 2   edad     4 non-null      int64
 3   salario  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [ ]:
df.describe() # Estadísticas descriptivas para variables cuantitativas

            edad      salario
count   4.000000     4.000000
mean   29.000000  2250.000000
std     4.966555   645.497224
min    23.000000  1500.000000
25%    26.750000  1875.000000
50%    29.000000  2250.000000
75%    31.250000  2625.000000
max    35.000000  3000.000000

In [ ]:
df.shape #(filas, columnas)

(4, 4)

In [ ]:
df['edad'] # Para imprimir la columna edad

0    23
1    30
2    35
3    28
Name: edad, dtype: int64

In [ ]:
df[['nombre', 'edad']] # Selección de columnas utilizando una lista con los respectivos nombres

   nombre  edad
0     Ana    23
1    Luis    30
2  Carlos    35
3   Marta    28

In [ ]:
df[df['edad'] > 25] # Selección de filas

   nombre    ciudad  edad  salario
1    Luis  Medellín    30     2000
2  Carlos      Cali    35     3000
3   Marta    Bogotá    28     2500

In [ ]:
df[(df['edad'] > 20) & (df['edad'] < 30)] #Selección de filas de edad entre 20 y 30 años

  nombre  ciudad  edad  salario
0    Ana  Bogotá    23     1500
3  Marta  Bogotá    28     2500

In [ ]:
data = {
    'nombre': ['Ana', 'Luis', 'Carlos', 'Marta', None],
    'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá', 'Cali'],
    'edad': [23, np.nan, 30, 35, 28],
    'salario': [1000, 2000, 3000, 2500, 1500]
}
data

{'nombre': ['Ana', 'Luis', 'Carlos', 'Marta', None],
 'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá', 'Cali'],
 'edad': [23, nan, 30, 35, 28],
 'salario': [1000, 2000, 3000, 2500, 1500]}

In [ ]:
data1 = pd.DataFrame(data)
data1

   nombre    ciudad  edad  salario
0     Ana    Bogotá  23.0     1000
1    Luis  Medellín   NaN     2000
2  Carlos      Cali  30.0     3000
3   Marta    Bogotá  35.0     2500
4    None      Cali  28.0     1500

In [ ]:
data1.isnull() #Valores faltantes

   nombre  ciudad   edad  salario
0   False   False  False    False
1   False   False   True    False
2   False   False  False    False
3   False   False  False    False
4    True   False  False    False

In [ ]:
data1.isnull().sum() # Suma los valores por columnas: 1 si es faltante, 0 si no.

nombre     1
ciudad     0
edad       1
salario    0
dtype: int64

In [ ]:
data2 = data1.dropna() #Elimina las filas con valores faltantes
data2

   nombre  ciudad  edad  salario
0     Ana  Bogotá  23.0     1000
2  Carlos    Cali  30.0     3000
3   Marta  Bogotá  35.0     2500

In [ ]:
data1.dropna(subset=['salario']) # Se eliminan las filas con valores faltantes,
# únicamente en la columna salario

   nombre    ciudad  edad  salario
0     Ana    Bogotá  23.0     1000
1    Luis  Medellín   NaN     2000
2  Carlos      Cali  30.0     3000
3   Marta    Bogotá  35.0     2500
4    None      Cali  28.0     1500

In [ ]:
data1['edad'] = data1['edad'].fillna(data1['edad'].mean()) #Rellena los valores faltantes con la media
data1["nombre"] = data1['nombre'].fillna('Desconocido')
data1

        nombre    ciudad  edad  salario
0          Ana    Bogotá  23.0     1000
1         Luis  Medellín  29.0     2000
2       Carlos      Cali  30.0     3000
3        Marta    Bogotá  35.0     2500
4  Desconocido      Cali  28.0     1500

In [ ]:
data1['ciudad'] = data1['ciudad'].replace('Bogotá', 'BOGOTA')
data1

        nombre    ciudad  edad  salario
0          Ana    BOGOTA  23.0     1000
1         Luis  Medellín  29.0     2000
2       Carlos      Cali  30.0     3000
3        Marta    BOGOTA  35.0     2500
4  Desconocido      Cali  28.0     1500

In [ ]:
data4 = data1['ciudad'].drop_duplicates() #Elimina los valores duplicados
data4

0      BOGOTA
1    Medellín
2        Cali
Name: ciudad, dtype: object

In [ ]:
data5 = {
    'nombre': ['Ana', 'Luis', 'Carlos', 'Marta', 'Juan'],
    'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá', 'Cali'],
    'edad': [23, 30, 35, 28, 23],
}
data5 = pd.DataFrame(data5)
data5

   nombre    ciudad  edad
0     Ana    Bogotá    23
1    Luis  Medellín    30
2  Carlos      Cali    35
3   Marta    Bogotá    28
4    Juan      Cali    23

In [ ]:
data6 = data5.drop_duplicates()
data6

   nombre    ciudad  edad
0     Ana    Bogotá    23
1    Luis  Medellín    30
2  Carlos      Cali    35
3   Marta    Bogotá    28
4    Juan      Cali    23

In [ ]:
import pandas as pd

dfn = pd.DataFrame({
    'id': [1, 2, 3, 4, ],
    'nombre': ['Ana', 'Luis', 'Carlos', 'Marta'],
    'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá'],
    'edad': [23, 30, 35, 28],
    'salario': [1000, 2000, 3000, 1500]
})
dfn

   id  nombre    ciudad  edad  salario
0   1     Ana    Bogotá    23     1000
1   2    Luis  Medellín    30     2000
2   3  Carlos      Cali    35     3000
3   4   Marta    Bogotá    28     1500

In [ ]:
dfn['salario_anual'] = dfn['salario'] * 12 # Aplicar función
dfn['edad_doble'] = dfn['edad'].apply(lambda x: x * 2)
dfn

   id  nombre    ciudad  edad  salario  salario_anual  edad_doble
0   1     Ana    Bogotá    23     1000          12000          46
1   2    Luis  Medellín    30     2000          24000          60
2   3  Carlos      Cali    35     3000          36000          70
3   4   Marta    Bogotá    28     1500          18000          56

In [ ]:
dfn = dfn.rename(columns={'edad': 'age'})
dfn

   id  nombre    ciudad  age  salario  salario_anual  edad_doble
0   1     Ana    Bogotá   23     1000          12000          46
1   2    Luis  Medellín   30     2000          24000          60
2   3  Carlos      Cali   35     3000          36000          70
3   4   Marta    Bogotá   28     1500          18000          56

In [ ]:
grupo = dfn.groupby('ciudad')['salario'].mean()
grupo

ciudad
Bogotá      1250.0
Cali        3000.0
Medellín    2000.0
Name: salario, dtype: float64

In [ ]:
ordenado = dfn.sort_values(by = 'age')
ordenado

   id  nombre    ciudad  age  salario  salario_anual  edad_doble
0   1     Ana    Bogotá   23     1000          12000          46
3   4   Marta    Bogotá   28     1500          18000          56
1   2    Luis  Medellín   30     2000          24000          60
2   3  Carlos      Cali   35     3000          36000          70

In [ ]:
dfn1 = pd.DataFrame({
    'id': [1, 2, 3, 4],
    'departamento': ['Ventas', 'IT', 'RRHH', 'MARKETING']})

merge = pd.merge(dfn, dfn1, on = 'id')
merge

   id  nombre    ciudad  age  salario  salario_anual  edad_doble departamento
0   1     Ana    Bogotá   23     1000          12000          46       Ventas
1   2    Luis  Medellín   30     2000          24000          60           IT
2   3  Carlos      Cali   35     3000          36000          70         RRHH
3   4   Marta    Bogotá   28     1500          18000          56    MARKETING

In [ ]:
valores = dfn.values
valores

array([[1, 'Ana', 'Bogotá', 23, 1000, 12000, 46],
       [2, 'Luis', 'Medellín', 30, 2000, 24000, 60],
       [3, 'Carlos', 'Cali', 35, 3000, 36000, 70],
       [4, 'Marta', 'Bogotá', 28, 1500, 18000, 56]], dtype=object)

In [ ]:
arr = np.array([10, 20, 30])
df = pd.DataFrame(arr)
df

    0
0  10
1  20
2  30

In [ ]:
import numpy as np


precios = np.array([12.50, 45.00, 8.90, 100.00, 15.50, 5.00])

# Método 1: np.sort() - Ordenar precios
precios_ordenados = np.sort(precios)
print("Precios de menor a mayor:", precios_ordenados)

# Método 2: np.mean() - Calcular el promedio
promedio = np.mean(precios)
print(f"Precio promedio: ${promedio:.2f}")

# Método 3: np.where() - Clasificar productos (Premium > $30)
clasificacion = np.where(precios > 30, 'Producto Premium', 'Producto Básico')
print("Clasificación de productos:", clasificacion)

Precios de menor a mayor: [  5.    8.9  12.5  15.5  45.  100. ]
Precio promedio: $31.15
Clasificación de productos: ['Producto Básico' 'Producto Premium' 'Producto Básico' 'Producto Premium'
 'Producto Básico' 'Producto Básico']

In [ ]:
import pandas as pd

# Datos: Ventas semanales
data = {
    'Vendedor': ['Juan', 'Maria', 'Pedro', 'Ana'],
    'Ventas': [1500, 2200, 900, 3100],
    'Region': ['Norte', 'Sur', 'Norte', 'Sur']
}
df = pd.DataFrame(data)

# Método 1: groupby() - Sumar ventas por región
ventas_region = df.groupby('Region')['Ventas'].sum()
print("Total de ventas por región:")
print(ventas_region)

# Método 2: sort_values() - Ordenar por ventas
mejor_vendedor = df.sort_values(by='Ventas', ascending=False)
print("\nVendedores ordenados por ventas:")
print(mejor_vendedor)

# Método 3: describe() - Resumen estadístico
print("\nResumen estadístico de ventas:")
print(df['Ventas'].describe())

Total de ventas por región:
Region
Norte    2400
Sur      5300
Name: Ventas, dtype: int64

Vendedores ordenados por ventas:
  Vendedor  Ventas Region
3      Ana    3100    Sur
1    Maria    2200    Sur
0     Juan    1500  Norte
2    Pedro     900  Norte

Resumen estadístico de ventas:
count       4.000000
mean     1925.000000
std       946.484724
min       900.000000
25%      1350.000000
50%      1850.000000
75%      2425.000000
max      3100.000000
Name: Ventas, dtype: float64

Conclusion:
NumPy vs. Pandas en Ciencia de Datos

Para la implementación de algoritmos de Ciencia de Datos y Machine Learning, la elección entre estas dos librerías no es opcional, sino complementaria. A continuación, presento sus características clave bajo un enfoque de rendimiento y aplicabilidad:

NumPy: El motor de cálculo numérico

NumPy es el estándar para la computación intensiva debido a su capacidad de vectorización, lo que permite ejecutar operaciones sobre arreglos completos sin necesidad de usar bucles for lentos.

Ventajas:

Eficiencia en memoria: Almacena datos de forma contigua en la memoria, lo que optimiza el acceso y la velocidad de procesamiento (al estar compilado en C).

Base de datos científica: Es la capa sobre la que se construyen algoritmos complejos de álgebra lineal, transformadas de Fourier y generación de números aleatorios.

Desventajas:

Rigidez de tipo: Obliga a que todos los elementos de un arreglo sean del mismo tipo (ej. solo integers o solo floats). Esto lo hace ineficiente para datos del mundo real que suelen ser "sucios" y mezclan etiquetas de texto con valores numéricos.

Falta de contexto: Los arreglos de NumPy no tienen nombres de columnas ni índices significativos, lo que obliga al programador a recordar qué significa cada posición o columna, aumentando el riesgo de errores lógicos.

Pandas: La herramienta de estructuración y limpieza

Pandas extiende la potencia de NumPy para trabajar con DataFrames, estructuras tabulares (similares a Excel o SQL) que permiten etiquetar datos.

Ventajas:

Gestión de datos heterogéneos: Permite manipular en una misma tabla números, fechas, categorías y texto, facilitando el trabajo con datasets del mundo real.

Potencia en limpieza: Incluye métodos nativos para gestionar datos faltantes (NaN), realizar joins (uniones) entre tablas y agrupar información mediante groupby, algo que sería extremadamente complejo y tedioso de programar desde cero en NumPy.

Desventajas:

Costo computacional: Debido a la flexibilidad y la sobrecarga que implican los índices y metadatos del DataFrame, Pandas es significativamente más lento y consume más memoria RAM que NumPy.

Limitaciones en Big Data: Al cargar todo el conjunto de datos en la memoria activa del equipo, no es apto para procesar archivos que excedan la capacidad de la memoria RAM disponible, obligando a buscar alternativas como el procesamiento distribuido en Spark.